# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zwX1TOc-4s8hkH7R901O2j86vX392xeQ
"""

Score=input().split()
count=0
for i in Score:
  if int(i)<60:
    count+=1
print(count)