# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14071TwDs_y2Du-cmhJxhWq4akK4G3cvt
"""

scores_str = input().split()
fail_count = 0

scores_int = [int(score) for score in scores_str]

for num in scores_int:
    if num < 60:
        fail_count += 1

print(fail_count)
print(max(scores_int))
print(min(scores_int))
total_score = 0

for score in scores_str:
    num = int(score)

    if num < 60:
        fail_count += 1

    total_score += num

average_score = total_score / len(scores_str)

print(fail_count)
print(average_score)

